### ISSUE TITLE
Inferencing the counting algorithm on static images 

### ISSUE THREAD

**Issue by aurea2022** [mohamedamine99/Object-tracking-and-counting-using-YOLOV8#2]
Hi..I would like to ask on how to use the codes to inference on static images. The yolo object counter OPP file has codes for videos. I am finding it a little challenging to use it for images.

**Comment by mohamedamine99** [comment]
Hi aurea2022,

To perform inference on static images using the YOLO object counter OOP code, you can follow these steps:

```py
# instanciating a YOLOv8_ObjectDetector instance
d = YOLOv8_ObjectDetector()

# running inference on a static image
r = d.predict_img('https://ultralytics.com/images/bus.jpg', verbose = True)
#print(r)

# plotting results in rgb space
a = r.plot()
plt.imshow(a[..., ::-1]) # [..., ::-1] : bgr --> rgb

```

Breaking it down into individual steps:

Let's now provide a detailed explanation of the code snippet above, breaking it down into individual steps:

1. Instantiating a `YOLOv8_ObjectDetector` instance:
   The first line of code creates an instance of the `YOLOv8_ObjectDetector` class and assigns it to the variable 'd'. You can customize the instantiation by providing additional parameters to the constructor.

2. Running inference on a static image:
   For that you can use the `predict_img` method of the `YOLOv8_ObjectDetector` instance. **You can check this method's documentation** in the [yOLOv8_Object_Counter_OOP.ipynb notebook](https://github.com/mohamedamine99/Object-tracking-and-counting-using-YOLOV8/blob/main/YOLOv8_Object_Counter_OOP.ipynb)

3. Plotting results in RGB space:
   - The third line of code creates a variable 'a' and assigns it the result of calling the default `plot()` method on the object detection output 'r'. This `plot` method is the default ultralytics method for displaying results. The visualization is represented in the default `BGR` color space.

   - The fourth line of code uses the `plt.imshow` to display the image with the detected objects. The `a[..., ::-1]` indexing reverses the color channels of the image, converting it from BGR to RGB format, which is commonly used for visualization purposes.

By following these steps, you can instantiate a YOLOv8 object detector, run inference on a static image, and visualize the detection results in RGB space.

The results should be as follows : 

![bus yolo results](https://github.com/mohamedamine99/Object-tracking-and-counting-using-YOLOV8/assets/86969450/dc02c497-5622-4f97-8a2e-a90d1d2edfe5)

For more details I highly encourage you to check the following links:
- [YOLOv8 official documentation](https://docs.ultralytics.com/modes/predict/)
- [yOLOv8_Object_Counter_OOP.ipynb notebook](https://github.com/mohamedamine99/Object-tracking-and-counting-using-YOLOV8/blob/main/YOLOv8_Object_Counter_OOP.ipynb) or [yolo_detect_and_count.py](https://github.com/mohamedamine99/Object-tracking-and-counting-using-YOLOV8/blob/main/yolo_detect_and_count.py) for more documentation about the custom classes and methods I implemented for this project.
- [YOLOv8_Object_Detection_procedural.ipynb](https://github.com/mohamedamine99/Object-tracking-and-counting-using-YOLOV8/blob/main/YOLOv8_Object_Detection_procedural.ipynb) for more details about how to use ultralytics' YOLOv8 on multiple targets including static images.( no OOP).

If you have any further questions or need additional clarification, please let me know.
